### ISSUE TITLE
pixelmonbank.admin.bypass bug

### ISSUE THREAD

**Issue by griffstack** [Lileep/PixelmonBank#8]
All of the other permissions seem to work fine, however the send bypass does not work to allow non-op players to use -f

1.5.2 - 1.16.5 - 9.1.10

**Comment by Lileep** [comment]
Thx for ur reply!
Will have a check later :)

**Comment by Lileep** [comment]
Confirmed.Will fix in next release

**Comment by Lileep** [comment]
Fixed in 1.5.4
